# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: FaceService.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='FaceService.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x11\x46\x61\x63\x65Service.proto\x1a\x1bgoogle/protobuf/empty.proto\"G\n\tImageData\x12\x12\n\nImageBytes\x18\x01 \x01(\x0c\x12\x0f\n\x07\x65motion\x18\x02 \x01(\x05\x12\x15\n\tembedding\x18\x03 \x03(\x01\x42\x02\x10\x01\x32H\n\rFaceDetection\x12\x37\n\x11SendProcessedData\x12\n.ImageData\x1a\x16.google.protobuf.Emptyb\x06proto3')
  ,
  dependencies=[google_dot_protobuf_dot_empty__pb2.DESCRIPTOR,])




_IMAGEDATA = _descriptor.Descriptor(
  name='ImageData',
  full_name='ImageData',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='ImageBytes', full_name='ImageData.ImageBytes', index=0,
      number=1, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='emotion', full_name='ImageData.emotion', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='embedding', full_name='ImageData.embedding', index=2,
      number=3, type=1, cpp_type=5, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=_b('\020\001'), file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=50,
  serialized_end=121,
)

DESCRIPTOR.message_types_by_name['ImageData'] = _IMAGEDATA
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

ImageData = _reflection.GeneratedProtocolMessageType('ImageData', (_message.Message,), {
  'DESCRIPTOR' : _IMAGEDATA,
  '__module__' : 'FaceService_pb2'
  # @@protoc_insertion_point(class_scope:ImageData)
  })
_sym_db.RegisterMessage(ImageData)


_IMAGEDATA.fields_by_name['embedding']._options = None

_FACEDETECTION = _descriptor.ServiceDescriptor(
  name='FaceDetection',
  full_name='FaceDetection',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=123,
  serialized_end=195,
  methods=[
  _descriptor.MethodDescriptor(
    name='SendProcessedData',
    full_name='FaceDetection.SendProcessedData',
    index=0,
    containing_service=None,
    input_type=_IMAGEDATA,
    output_type=google_dot_protobuf_dot_empty__pb2._EMPTY,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_FACEDETECTION)

DESCRIPTOR.services_by_name['FaceDetection'] = _FACEDETECTION

# @@protoc_insertion_point(module_scope)
