# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import FaceService_pb2 as FaceService__pb2
from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2


class FaceDetectionStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.SendProcessedData = channel.unary_unary(
        '/FaceDetection/SendProcessedData',
        request_serializer=FaceService__pb2.ImageData.SerializeToString,
        response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
        )


class FaceDetectionServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def SendProcessedData(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_FaceDetectionServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'SendProcessedData': grpc.unary_unary_rpc_method_handler(
          servicer.SendProcessedData,
          request_deserializer=FaceService__pb2.ImageData.FromString,
          response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'FaceDetection', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
